---
- name: Create couchdb service
  become: yes
  shell: docker service create  \
         --replicas 4  \
         --name couchdbservice \
         --publish mode=host,target=5984,published=5984  \
         --publish mode=host,target=4369,published=4369 \  
         --publish mode=host,target=9000,published=9000 \
         -e COUCHDB_ARGS_FILE=/opt/couchdb/etc/local.d/vm.args \
         --mount type=volume,source=couchdb_volume,destination=/opt/couchdb/data \
         --mount type=volume,source=couchdb_config,destination=/opt/couchdb/etc/local.d \ 
         -e COUCHDB_USER=admin \
         -e COUCHDB_PASSWORD=password  \
         -d couchdb

- name: mkdir couchDB_cluster
  become: yes
  shell: mkdir couchDB_cluster

- name: Set up cluster
  become: yes
  blockinfile:
    create: yes
    path: couchDB_cluster/couch.sh
    block: |
      export declare -a nodes=({{manager}} {{worker1}} {{worker2}} {{worker3}})
      export masternode=`echo ${nodes} | cut -f1 -d' '`
      export declare -a othernodes=`echo ${nodes[@]} | sed s/${masternode}//`
      export size=${#nodes[@]}
      export user=admin
      export pass=password
      for node in ${othernodes} 
      do
      curl -XPOST "http://${user}:${pass}@${masternode}:5984/_cluster_setup" \
      --header "Content-Type: application/json"\
      --data "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
             \"username\": \"${user}\", \"password\":\"${pass}\", \"port\": \"5984\",\
             \"remote_node\": \"${node}\", \"node_count\": \"$(echo ${nodes[@]} | wc -w)\",\
             \"remote_current_user\":\"${user}\", \"remote_current_password\":\"${pass}\"}"
      done
      for node in ${othernodes}
      do
      curl -XPOST "http://${user}:${pass}@${masternode}:5984/_cluster_setup"\
      --header "Content-Type: application/json"\
      --data "{\"action\": \"add_node\", \"host\":\"${node}\",\
             \"port\": \"5984\", \"username\": \"${user}\", \"password\":\"${pass}\"}"
      done
      curl -XPOST "http://${user}:${pass}@${masternode}:5984/_cluster_setup"\
       --header "Content-Type: application/json" --data "{\"action\": \"finish_cluster\"}"

- name: change permission
  become: yes
  shell: chmod +wx couchDB_cluster/couch.sh

- name: Run couch shell
  become: yes
  shell: couchDB_cluster/couch.sh


