---
- name: Create couchdb service
  become: yes
  shell: docker service create  \
         --replicas 4  \
         --name couchdbservice \
         --publish mode=host,target=5984,published=5984  \
         --publish mode=host,target=4369,published=4369 \  
         --publish mode=host,target=9000,published=9000 \
         -e COUCHDB_ARGS_FILE=/opt/couchdb/etc/local.d/vm.args \
         --mount type=volume,source=couchdb_volume,destination=/opt/couchdb/data \
         --mount type=volume,source=couchdb_config,destination=/opt/couchdb/etc/local.d \ 
         -e COUCHDB_USER=admin \
         -e COUCHDB_PASSWORD=password  \
         -d couchdb








