- hosts: localhost
  vars_files:
    - host_vars/main.yaml
  gather_facts: false

  tasks:
    - name: Get permission
      raw: sudo chmod 666 /var/run/docker.sock

  roles:
    - role: volumes
    - role: web
