# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol_master
    vol_size: 20
  - vol_name: vol_worker1
    vol_size: 20
  - vol_name: vol_worker2
    vol_size: 20


# Security group
security_groups:
  - name: project_ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: project_http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: project_couchdb
    description: "Project security group for Couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: master
    volumes: ['vol_master']
  - name: worker1
    volumes: ['vol_worker1']
  - name: worker2
    volumes: ['vol_worker2']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: id_Cassie
instance_flavor: uom.mse.2c9g
