# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vegan-vol-1-1
    vol_size: 10
  - vol_name: vegan-vol-1-2
    vol_size: 10
  - vol_name: vegan-vol-2-1
    vol_size: 10
  - vol_name: vegan-vol-2-2
    vol_size: 10

# Security group
security_groups:
  - name: vegan_ssh
    description: "Vegan security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: vegan_http
    description: "Vegan security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: vegan-1
    volumes: ['vegan-vol-1-1', 'vegan-vol-1-2']
  - name: vegan-2
    volumes: ['vegan-vol-2-1', 'vegan-vol-2-2']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: id_Cassie
instance_flavor: uom.mse.2c9g
