- hosts: Docker
  vars_files:
    - host_vars/docker.yaml
  gather_facts: false

  roles:
    - role: common
    - role: volumes
    - role: docker

- hosts: manager
  gather_facts: false
  roles:
    - role: swarmmanager

- hosts: worker
  gather_facts: false
  roles:
    - role: swarmworkers